### PR TITLE
Move requests requirement

### LINKED ISSUE #126: Missing dependency on requests
Was just doing a clean setup before making a PR and I noticed that requests should be in the main requirements.txt, not requirements-dev.txt.

To reproduce:

```
# Make env
$ pip install whotracksme
$ python

Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux                                                                                                  Type "help", "copyright", "credits" or "license" for more information.
>>> from whotracksme.data.loader import DataSource             
Traceback (most recent call last):                                                                                                               
  File "<stdin>", line 1, in <module>        
  File "/home/bird/Dev/birdsarah/whotracks.me/whotracksme/data/__init__.py", line 2, in <module>
    from whotracksme.data.loader import (         
  File "/home/bird/Dev/birdsarah/whotracks.me/whotracksme/data/loader.py", line 7, in <module>
    from whotracksme.data.db import load_tracker_db, create_tracker_map
  File "/home/bird/Dev/birdsarah/whotracks.me/whotracksme/data/db.py", line 2, in <module>
    import requests                                  
ModuleNotFoundError: No module named 'requests'   
```

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes #126

### CODE REVIEW

**Comment by remusao** [comment]
Hi @birdsarah! Thank you so much for your contribution! Could you maybe add `requests` as an `install_requires` entry in the setup.py as well please? Also, I tend to consider `requirements-dev.txt` as a super set of `requirements.txt`, so maybe we could leave `requests` in there as well, so that people can either do `pip install -r requirements.txt` or `pip install -r requirements-dev.txt` but not both. What do you think?

**Comment by birdsarah** [comment]
>  Could you maybe add requests as an install_requires entry in the setup.py as well please?

I just went a step further and had setup.py read from requirements, which is what I commonly do. No stress if you don't want to do this.

**Comment by remusao** [comment]
> I just went a step further and had setup.py read from requirements, which is what I commonly do. No stress if you don't want to do this.

I have nothing against this, although there is usually one distinction which I tend to make between the dependencies in the `setup.py` and `requirements.txt`. In `setup.py` we specify dependencies which are directly used in the code (e.g.: `pandas`, `docopt`, `requests`), but not necessarily transitive dependencies (e.g.: `numpy`, which is a dependency of `pandas` but is not used directly in the code); this is used to express what packages we rely upon (without necessarily specifying a version of them). The requirements file are currently used a lock file, including all transitive dependencies as well as their exact version; this is used so that we can express the exact environment needed to work with the project. My fear is that if we merge both, we loose track of which dependencies are actually imported in the code, and which ones are transitive dependencies. But I have to admit that this is not ideal and the workflow is a bit cumbersome. Maybe something like `pipenv` with a lock file would make more sense to replace the requirements files...

**Comment by birdsarah** [comment]
Yeah...There's no great answers here. Only trade-offs. 

If you're pinning, you're sure that, that combination of package versions work and your code runs and so you can pass on that guarantee to consumers of your package.The downside is that if you're not keeping up with package updates, you're holding your consumers back. 

I'll revert this and let you figure out your process in your own PR.

**Pull request merged**
